name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn --batch-mode clean package

      - name: Upload shaded JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: md2mermaid-jar
          path: target/md2mermaid-*-shadow.jar
          # Delete after 1 day
          retention-days: 1
